### PR TITLE
Current Leiningen Support

### PR DESCRIPTION
**Pull request by jaidetree**
- Added current Leiningen support with dynamic imports.
- Created leiningen test
- Updated root project so we can run `lein with-profile test check` to make sure library will run

## Experiments
- Added a check to see if REBL exists and prints a warning if it is not found at time of repl launch.

### CODE REVIEW

**Comment by jaidetree** [comment]
https://github.com/jayzawrotny/nrebl.middleware/tree/lein

I was able to get your lein branch working after some small tweaks. However, I couldn't get it to work using your recommended `profiles.clj`. I did manage it with a local `project.clj`.

```clj
(defproject test-app "0.1.0-SNAPSHOT"
  :dependencies [[rickmoynihan/nrebl.middleware "0.1.0-SNAPSHOT"]
                 [org.clojure/clojure "1.10.0-RC4"]
                 [org.clojure/core.async "0.4.490"]]
  :resource-paths ["resources/REBL-0.9.109.jar"]
  :repl-options {:nrepl-middleware [nrebl.middleware/wrap-nrebl]})
```

**Comment by RickMoynihan** [comment]
Thanks.  I'll try and look at this on Friday night or at the weekend.

**Comment by jaidetree** [comment]
- Added filtering for Cursive eval requests which can be quite noisy

screen shot 2018-12-12 at 11 37 26 pm

**Comment by jaidetree** [comment]
Dropping this PR in favor of smaller ones.

**Pull request closed without merging**
