### PR TITLE
Ensure wrap-nrebl is applied after nREPL's printing middleware 2

### PR DESCRIPTION
**Pull request by RickMoynihan**
Force a better ordering on middlewares to ensure we can rely on them with regards to eval/print etc, and add support for nrepl 0.6.0 and leiningen 2.9.0

### CODE REVIEW

**Comment by maxthoursie** [comment]
This works great for me using _Cursive 1.8.1-eap3_ which includes _lein 1.9.0_!

In particular, non-pr-able things works, e.g. I can successfully evaluate 
```clojure
(java.net.URL. "http://clojure.org")
```
and see the web page in the REBL.

Thank you!

**Comment by bbatsov** [comment]
Well, I guess you should merge this at some point. :-) Especially given the release of Lein 2.9.

**Comment by lilactown** [comment]
Can we merge this?

**Comment by bbatsov** [comment]
I think at this point there's no need to support tools.nrepl anymore. Everyone moved on to the new nrepl. Yeah, it'd be great if this was merged (in one form or another).

**Comment by RickMoynihan** [comment]
Sorry for the delay on this. I'll try and take a look at this when I find some time (new born baby).

Also FYI @bbatsov I'm still up for migrating this into your nrepl team when I find some time.

**Comment by bbatsov** [comment]
@RickMoynihan Roger that!

**Pull request merged**
